apiVersion: v1
kind: ServiceAccount
type: kubernetes.io/service-account-token
metadata:
  name: app
  annotations:
    kubernetes.io/service-account.name: "app"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app
rules:
- apiGroups: ["*"]
  resources: ["nodes","nodes/proxy","nodes/metrics","services","endpoints","pods","ingresses","configmaps"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app
subjects:
- kind: ServiceAccount
  name: app
