apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      serviceAccountName: querier
      containers:
      - name: app
        securityContext:
          runAsUser: 0
        readinessProbe:
          httpGet: 
            path: /health
        livenessProbe:
          httpGet: 
            path: /health
        envFrom:
        - configMapRef:
            name: querier-configmap