apiVersion: v1
kind: ConfigMap
metadata:
  name: jcasc-config
data:
  jcasc.yaml: |-
    jenkins:
      systemMessage: "100% Immutable, All configuration for this jenkins is done as code (JCasC)"
      agentProtocols:
      - "JNLP4-connect"
      - "Ping"
      numExecutors: 5
      labelString: "master"
      securityRealm:
        local:
          allowsSignup: false
          users:
          - id: admin
            password: rahasia
      authorizationStrategy:
        globalMatrix:
          permissions:
            - "Overall/Administer:admin"
            - "Overall/Read:authenticated"
      remotingSecurity:
        enabled: true
      clouds:
      - kubernetes:
          containerCapStr: "50"
          jenkinsTunnel: "jenkins-slave-svc.jenkins:40001"
          jenkinsUrl: "http://jenkins-master-svc.jenkins:8080"
          maxRequestsPerHostStr: "32"
          name: "kubernetes"
          namespace: "jenkins"
          serverUrl: "https://34.101.59.138"
      slaveAgentPort: 40001
    security:
      queueItemAuthenticator:
        authenticators:
        - global:
            strategy: triggeringUsersAuthorizationStrategy
    unclassified:
      location:
        url: https://jenkins.pepago.my.id
    jobs:
    - script: >
        pipelineJob("initial_dsl_job_pipeline") {
          definition {
              cpsScm {
                  scm {
                      git{
                        remote {
                          url("https://github.com/launathiel/jenkins-dsl.git")
                          scriptPath("Jenkinsfile")
                        }
                        branch('*/main')
                      }
                  }
              }
            }
        }