apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins-config
data:
  initPlugins.sh: |-
    cp /var/jenkins_config/plugins.txt /var/jenkins_home;
    rm -rf /usr/share/jenkins/ref/plugins/*.lock
    jenkins-plugin-cli --plugin-file /var/jenkins_home/plugins.txt --plugin-download-directory /usr/share/jenkins/ref/plugins --latest false --verbose
    yes n | cp -i /usr/share/jenkins/ref/plugins/* /var/jenkins_plugins/;
  plugins.txt: |-
    authorize-project:1.4.0
    ansible:1.1
    blueocean:1.27.4
    cloudbees-folder:6.848.ve3b_fd7839a_81
    configuration-as-code:1700.v6f448841296e
    credentials-binding:631.v861c06d062b_4
    generic-webhook-trigger:1.84
    git:5.0.1
    git-parameter:0.9.17
    github-branch-source:1598.v91207e9f9b_4a_
    job-dsl:1.85
    kubernetes:4029.v5712230ccb_f8
    pam-auth:1.7
    role-strategy:3.2.0
    ssh-slaves:1.806.v2253cedd3295
    timestamper:1.17
    workflow-aggregator:590.v6a_d052e5a_a_b_5
    workflow-job:1342.v046651d5b_dfe
    workflow-cps:3774.v4a_d648d409ce
    ws-cleanup:0.41
