apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: launathiel@gmail.com
    privateKeySecretRef:
      name: backend-tls
    solvers:
    - http01:
        ingress:
          class: ingress-gateway