apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-devops-labs
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app/inventory
    repoURL: https://github.com/launathiel/DevOpsFullLabs.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true