apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.5.1
  name: ingress-nginx-controller
  namespace: ingress
data:
  allow-snippet-annotations: "true"
  compute-full-forwarded-for: "true"
  proxy-real-ip-cidr: 172.20.0.0/16, 10.0.0.0/16, 192.168.10.0/24, 192.168.100.0/24, 10.8.0.0/24, 192.168.20.0/24
  se-forwarded-headers: "true"
  disable-access-log: "true"
---
